---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 50

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: deps-3.6
  pull: always
  image: python:3.6
  commands:
  - make install
  volumes:
  - name: cached-poetry
    path: /root/.poetry
  - name: cached-deps
    path: /root/.cache/pypoetry/virtualenvs

- name: deps-3.7
  pull: always
  image: python:3.7
  commands:
  - make install
  volumes:
  - name: cached-poetry
    path: /root/.poetry
  - name: cached-deps
    path: /root/.cache/pypoetry/virtualenvs

- name: lint-3.7
  pull: always
  image: python:3.7
  commands:
  - make lint
  volumes:
  - name: cached-poetry
    path: /root/.poetry
  - name: cached-deps
    path: /root/.cache/pypoetry/virtualenvs

- name: test-3.6
  pull: always
  image: python:3.6
  commands:
  - make test
  environment:
    NATS_URL: nats://nats:4222
  volumes:
  - name: cached-poetry
    path: /root/.poetry
  - name: cached-deps
    path: /root/.cache/pypoetry/virtualenvs

- name: test-3.7
  pull: always
  image: python:3.7
  commands:
  - make test
  - make codecov
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
    NATS_URL: nats://nats:4222
  volumes:
  - name: cached-poetry
    path: /root/.poetry
  - name: cached-deps
    path: /root/.cache/pypoetry/virtualenvs

- name: lint/test completed
  pull: always
  image: appleboy/drone-telegram
  environment:
    PLUGIN_MESSAGE: "{{#success build.status}}\n  `{{repo.name}}` build {{build.number}} succeeded. Good job.\n{{else}}\n  `{{repo.name}}` build {{build.number}} failed. Fix me please.\n{{/success}}\n"
    PLUGIN_TO:
      from_secret: TELEGRAM_CHAT_ID
    PLUGIN_TOKEN:
      from_secret: TELEGRAM_BOT_TOKEN
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
    status:
    - success
    - failure

- name: publish
  pull: always
  image: python:3.7
  commands:
  - make publish
  environment:
    PYPI_PASSWORD:
      from_secret: PYPI_PASSWORD
    PYPI_USERNAME:
      from_secret: PYPI_USERNAME
  volumes:
  - name: cached-poetry
    path: /root/.poetry
  - name: cached-deps
    path: /root/.cache/pypoetry/virtualenvs
  when:
    event:
    - tag

- name: publish completed
  pull: always
  image: appleboy/drone-telegram
  environment:
    PLUGIN_MESSAGE: "{{#success build.status}}\n  `{{repo.name}}` publish {{build.tag}} succeeded. Good job.\n{{else}}\n  `{{repo.name}}` publish {{build.tag}} failed. Fix me please.\n{{/success}}\n"
    PLUGIN_TO:
      from_secret: TELEGRAM_CHAT_ID
    PLUGIN_TOKEN:
      from_secret: TELEGRAM_BOT_TOKEN
  when:
    event:
    - tag
    status:
    - success
    - failure

services:
- name: nats
  pull: always
  image: nats

volumes:
- name: cached-poetry
  temp: {}
- name: cached-deps
  temp: {}

...
