version: "3.6"

services:
  nats-plain:
    image: nats:2-alpine
    ports:
      - 4222:4222
  nats-tls:
    image: nats:2-alpine
    ports:
      - 4224:4222
    volumes:
      - ./docker-tls-entrypoint.sh:/usr/local/bin/docker-tls-entrypoint.sh:ro
    entrypoint:
      - /usr/local/bin/docker-tls-entrypoint.sh
