name: default

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v1
        with:
          poetry-version: 1.0.0
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-poetry-
      - run: make install-deps
      - run: make lint
        if: matrix.python-version == 3.8
      - run: docker-compose up -d && sleep 10
      - run: make test
      - run: docker-compose down
        if: always()
      - run: make codecov
        if: matrix.python-version == 3.8
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
