name: watch-started

on:
  watch:
    types: [started]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: ${{ github.repository }} starred!
